import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NavMenu } from "@/components/NavMenu";
import Providers from "@/shared/providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div
            className="relative flex h-screen w-screen flex-col bg-background
            text-text"
          >
            <header
              className="fixed flex h-20 w-full items-center bg-background/60
              text-text shadow shadow-shadow backdrop-blur-md"
            >
              <NavMenu />
            </header>
            <main className="flex-1 overflow-y-auto pt-20">
              <div className="container mx-auto">{children}</div>
            </main>
            <footer></footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
